# Generated by Django 6.0.3 on 2026-03-12 02:24

import agents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_rename_team_to_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspaceinvite',
            name='expires_at',
            field=models.DateTimeField(default=agents.models._default_invite_expiry),
        ),
        migrations.AlterField(
            model_name='workspaceinvite',
            name='token',
            field=models.CharField(default=agents.models._generate_invite_token, max_length=64, unique=True),
        ),
    ]
