# Generated by Django 5.0.10 on 2026-03-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_workspace_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='team_run_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
