# Generated by Django 5.0.10 on 2026-03-12 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_executionlog_team_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notification_channel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='agents.client'),
        ),
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cron_expression', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('notification_channel', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agents.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.client')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agents.agentteam')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agents.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_run_id', models.CharField(max_length=100)),
                ('result_so_far', models.TextField()),
                ('prompt', models.TextField()),
                ('platform', models.CharField(max_length=20)),
                ('platform_channel_id', models.CharField(blank=True, max_length=100)),
                ('platform_message_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decided_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agents.agent')),
                ('next_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agents.agent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='agents.agentteam')),
            ],
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agents.agent')),
            ],
            options={
                'unique_together': {('agent', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TeamMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agents.agentteam')),
            ],
            options={
                'unique_together': {('team', 'key')},
            },
        ),
    ]
