# Generated by Django 6.0.3 on 2026-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_threadmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmessage',
            name='thread_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['platform', 'thread_id'], name='agents_thre_platfor_b410cc_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['platform', 'thread_id', '-created_at'], name='agents_thre_platfor_d49dad_idx'),
        ),
    ]
