# Generated by Django 5.0.10 on 2026-03-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_sdk_session_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentteam',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('workspace', 'name')},
        ),
    ]
