# Generated by Django 6.0.3 on 2026-03-16 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agentteam_name_alter_agent_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_date', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('participants', models.JSONField(default=list)),
                ('audio_filename', models.CharField(blank=True, max_length=500)),
                ('whisper_model', models.CharField(default='small', max_length=20)),
                ('audio_source', models.CharField(choices=[('system', 'System Audio'), ('mic', 'Microphone'), ('upload', 'Upload'), ('import', 'Import')], default='upload', max_length=20)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='agents.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='agents.workspace')),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('summary', 'Summary'), ('action_items', 'Action Items'), ('follow_up_email', 'Follow-up Email'), ('proposal', 'Proposal'), ('custom', 'Custom')], max_length=30)),
                ('custom_prompt', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_results', to='agents.agent')),
                ('execution_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.executionlog')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_results', to='agents.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('segments', models.JSONField(default=list)),
                ('language', models.CharField(default='ko', max_length=10)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='agents.meeting')),
            ],
        ),
    ]
