# Generated by Django 5.0.10 on 2026-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_meeting_meetingagentresult_meetingtranscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentteam',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='agentteam',
            unique_together={('workspace', 'name')},
        ),
    ]
